#!/bin/bash

Mem=$(vmstat -s | sed -n 2p | sed s/[^0-9]//g)
Mem=$(echo "${Mem}/1024" | bc -l)

MEMG=$(echo "${Mem}/1024" | bc -l)
MEMG=$(printf "%01d" "${MEMG}")
MEMM=$(printf "%02d" $(echo "${Mem}/10 - 102*${MEMG}" | bc -l))

echo "<span color='#c55a2b'><span font='FontAwesome'>""</span>" ${MEMG}.${MEMM} / 7.7"</span>"

