#!/bin/bash

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  amixer -D pulse sset Master 5%+
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  amixer -D pulse sset Master toggle
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  amixer -D pulse sset Master 5%-
fi

statusLine=$(amixer -D pulse get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  STATUS=${volume}
else
  STATUS="off"
fi

echo "<span color='#96531d'>VOL: </span><span color='#c16b26'>${STATUS}%</span>"
