#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "<span color='#c2871f'><span font='FontAwesome'>""</span>" ${BATTERY_POWER}%-"</span>"
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo "<span color='#c2871f'><span font='FontAwesome'>""</span>" ${BATTERY_POWER}%+"</span>"
else
  echo "<span color='#c2871f'><span font='FontAwesome'>""</span>" ${BATTERY_POWER}%"</span>"
fi

