#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  STATUS="+"
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  STATUS="-"
else
  STATUS=" "
fi

echo "<span color='#96531d'>BAT: </span><span color='#c16b26'>${BATTERY_POWER}%‌‌‌‌‌‌‌‌‌‌‌‌‌${STATUS} </span>"
