#!/bin/bash

Mem=$(vmstat -s | sed -n 2p | sed s/[^0-9]//g)
TotalMem=$(vmstat -s | sed -n 1p | sed s/[^0-9]//g)

Mem=$(echo "scale=1;${Mem}/1048576" | bc -l)
TotalMem=$(echo "scale=1;${TotalMem}/1048576" | bc -l)

echo "<span color='#96531d'>RAM: </span><span color='#c16b26'>${Mem} / ${TotalMem}</span>"
